server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examination?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: xl2442356950...
logging:
  level:
    cn.xl.examination: debug
dirPath: D:/upload
markerhub:
  jwt:
    header: Authorization
    expire: 86400  # 1天
    secret: jinknaskwnga3t903wkgasnn124nag93
