server:
  port: 9090
  error:
    include-exception: true
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://192.168.5.153:3306/examination?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: xl2442356950...
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  resources:
    static-locations: file:D:/upload
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    cn.xl.examination: debug
certificatePath: "D:/upload/certificate/"
markerhub:
  jwt:
    header: Authorization
    expire: 86400  # 1天
    secret: jinknaskwnga3t903wkgasnn124nag93
mybatis:
  configuration:
    map-underscore-to-camel-case: true

video-path: "D:/upload/video/"
image-path: "D:/upload/image/"

